# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20171103_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
