# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20171109_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='dislikes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
