# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180416_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='judged',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
